apiVersion: v1
kind: Pod
metadata:
  # Unique key of the Job instance
  name: pending-pod
spec:
  containers:
  - name: pod
    image: ubuntu
    command: ["echo"]
    args: ["done"]
    resources:
      limits:
        cpu: "4"
      requests:
        cpu: "2"
    # The cluster should not schedule this pod because the pod does not set torelations.
